apiVersion: batch/v1
kind: CronJob
metadata:
  name: qi
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-container
            image:  {{ .Values.image.repository}}:{{ .Values.image.tag }}
            env:
            - TOKEN: {{ .Values.secret.TOKEN }}
            - CHATID: {{ .Values.secret.CHATID }}

            command: ["python3 main.py"]
          restartPolicy: OnFailure
