apiVersion: batch/v1
kind: CronJob
metadata:
  name: qijob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-container
            image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
            env:
            - name: TOKEN
              value: "{{ .Values.secret.TOKEN }}"
            - name: CHATID
              value: "{{ .Values.secret.CHATID }}"
          —Åommand: ["python3 main.py"]
          restartPolicy: OnFailure
