apiVersion: batch/v1
kind: CronJob
metadata:
  name: qijob
spec:
  schedule: "0 */8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          
          - name: my-container
            image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
            command: ["python3"]
            args: ["/app/main.py"]
            env:
            - name: TOKEN
              value: "{{ .Values.secret.TOKEN }}"
            - name: CHATID
              value: "{{ .Values.secret.CHATID }}"
          restartPolicy: OnFailure
