apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:  
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-container
            image:  {{ .Values.image.repository}}:{{ .Values.image.tag }}
            command: ["python3 main.py"]
          restartPolicy: OnFailure
