name: cicd-qi

on: push

env:
  TARGETARCH: amd64
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
                          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: registry.hub.docker.com
      - name: Build&Push
        env:
          APP: "qi"
        run: make image push TARGETARCH=$TARGETARCH
      - name: Clean
        run: make clean TARGETARCH=$TARGETARCH
